-- 创建bookmark表
CREATE TABLE `bookmark` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '书签名称',
  `url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '书签URL',
  `icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '书签图标',
  `category` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分类',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '描述',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `idx_name` (`name`) COMMENT '名称索引',
  INDEX `idx_category` (`category`) COMMENT '分类索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书签表';

-- 插入相关数据
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('腾讯元宝', 'https://yuanbao.tencent.com/chat/naQivTmsDa?yb_channel=3003', 'https://cdn-bot.hunyuan.tencent.com/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('DeepSeek', 'https://chat.deepseek.com/', 'https://cdn.deepseek.com/chat/icon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('ChatGPT', 'https://chatgpt.com/', 'https://cdn.oaistatic.com/assets/favicon-miwirzcw.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Claude', 'https://www.anthropic.com/claude', 'https://www.anthropic.com//images/icons/favicon-32x32.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Grok', 'https://x.ai/', 'https://x.ai/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('通义千问', 'https://tongyi.aliyun.com/qianwen/', 'https://img.alicdn.com/imgextra/i4/O1CN01EfJVFQ1uZPd7W4W6i_!!6000000006051-2-tps-112-112.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Kimi助手', 'https://kimi.moonshot.cn/', 'https://statics.moonshot.cn/kimi-chat/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('文心一言', 'https://yiyan.baidu.com/', 'https://nlp-eb.cdn.bcebos.com/logo/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('豆包', 'https://www.doubao.com/chat/', 'https://lf-flow-web-cdn.doubao.com/obj/flow-doubao/doubao/web/logo-icon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('海螺问问', 'https://hailuoai.com/chat', 'https://chat.minimaxi.com/assets/logo/favicon.png?v=3');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('跃问', 'https://yuewen.cn/chats/new', 'https://yuewen.cn/svg/favicon.svg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('秘塔搜索', 'https://metaso.cn/', 'https://metaso.cn/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('360AI搜索', 'https://www.sou.com/', 'https://www.sou.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('扣子', 'https://www.coze.cn/', 'https://lf-coze-web-cdn.coze.cn/obj/coze-web-cn/obric/coze/favicon.1970.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('即梦', 'https://jimeng.jianying.com/ai-tool/home​', 'https://lf3-lv-buz.vlabstatic.com/obj/image-lvweb-buz/common/images/dreamina-v5.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('通义万相', 'https://tongyi.aliyun.com/wanxiang/', 'https://alidocs.oss-accelerate.aliyuncs.com/res/oJGq76v5aMRynAKe/img/1b1b81ce-1625-4851-b015-09eb7b99872f.svg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('阿里堆友', 'https://d.design/ai/edit?entry=HOME&mode=lite', 'https://img.alicdn.com/imgextra/i2/O1CN01chTRfM1RHRCkxMMSn_!!6000000002086-0-tps-200-200.jpg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('可灵', 'https://kling.kuaishou.com/', 'https://s2-111386.kwimgs.com/bs2/mmu-aiplatform-temp/kling/kling-logo.png?x-oss-process=image/resize,m_mfit,w_50');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('即梦', 'https://jimeng.jianying.com/ai-tool/home', 'https://jimeng.jianying.com/ai-tool/home/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('佐糖', 'https://picwish.cn/?apptype=aps-pin', 'https://qncdn.aoscdn.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Canva', 'https://www.canva.cn/', 'https://static.canva.cn/static/images/favicon-1.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('稿定设计', 'https://www.gaoding.com/', 'https://cdn.dancf.com/fe-assets/20230811/logo/favicon@w64.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('美图设计室', 'https://www.designkit.com/', 'https://cdn.dancf.com/fe-assets/20230811/logo/favicon@w64.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('标小志', 'https://www.logosc.cn/', 'https://www.logosc.cn/img/logo-icons/logosc-new.svg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Looka', 'https://looka.com/', 'https://www.designkit.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('LogoDiffusion', 'https://logodiffusion.com/', 'https://cdn.prod.website-files.com/67319ecc5a80fcb0f18f2e74/673dddcbc136fc622fbbb019_Group%2040393.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('anime', 'https://anime-pictures.net/', 'https://anime-pictures.net/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('极简壁纸', 'https://bz.zzzmh.cn/index', 'https://bz.zzzmh.cn/img/icons/favicon-32x32.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('至美', 'https://zhutix.com/wallpaper/', 'https://zhutix.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('哲风壁纸', 'https://www.haowallpaper.com/', 'https://www.haowallpaper.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('壁纸湖', 'https://bizihu.com/?www.xijitu.com=1', 'https://bizihu.com/fliee/ico.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('必应壁纸', 'https://bing.xinac.net/?www.xijitu.com=1', 'https://s.xinac.net/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('4K壁纸网', 'https://www.bizhi99.com/3840x2160/', 'https://www.bizhi99.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('中关村壁纸', 'http://desk.zol.com.cn/', 'https://desk.zol.com.cn/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Pexels', 'https://www.pexels.com/zh-cn/', 'https://www.pexels.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('壁纸汇', 'https://www.bizhihui.com/', 'https://s.panlai.com/images/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Wallspic', 'https://wallspic.com/cn', 'https://wallspic.com/static/images/favicon/favicon-32x32.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('wallpaperscraft', 'https://wallpaperscraft.com/', 'https://wallpaperscraft.com/public/img/general/favicon.ico?v=1739404bd');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('BeautyYourDesktop', 'https://www.10wallpaper.com/', 'https://wallpaperscraft.com/public/img/general/favicon.ico?v=1739404bd');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('商量', 'https://chat.sensetime.com/', 'https://sensechat-ml.aoss.cn-sh-01.sensecoreapi-oss.cn/chat/prod/wb/favicon_ml.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('ClearPNG', 'https://www.cleanpng.com/', 'https://www.cleanpng.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('GameWallpapers', 'https://www.gamewallpapers.com/', 'https://www.cleanpng.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('WallHere 壁纸库', 'https://wallhere.com/', 'https://www.gamewallpapers.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('至美壁纸', 'https://zhutix.com/wallpaper/', 'https://zhutix.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('彼岸图网', 'https://pic.netbian.com/', 'https://pic.netbian.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('美化你的桌面', 'https://10wallpaper.com/cn/', 'https://10wallpaper.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Wallpapers', 'https://www.goodfon.com/', 'https://www.goodfon.com/static/favicon.svg?v=16');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Social Wallpapering', 'https://www.socwall.com/', 'https://www.socwall.com/images/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('天堂磁力', 'https://tt6.ttcl.cc/', 'https://tt6.ttcl.cc/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('磁力星球', 'https://so5.xingqiu.icu/', 'https://so5.xingqiu.icu/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('BT1027', 'https://bt1207gb.top/', 'https://prod.b5.howcdn.com/img/bt1207/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('磁力狐', 'https://bt31.foxs.vip/', 'https://i.loli.net/2021/10/18/7T4bMNpPDGRkyCV.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('无极磁力', 'https://xcili.net/', 'https://xcili.net/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('Yiove磁力搜索', 'https://bt.iaaaaa.com/', 'https://bt.iaaaaa.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('磁力多', 'https://ou.dobt.top/', 'https://ou.dobt.top/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('SkrBT', 'https://skrbtgb.top/', 'https://prod.b5.howcdn.com/img/skrbt/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('BT联盟', 'https://btlm.info/', 'https://btlm.info/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('磁力帝', 'https://kueawljv.1122128.xyz/', 'https://btlm.info/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('豌豆PRO', 'https://wandou.la/', 'https://www.wandou.la/_next/static/media/headlogo.84672dbf.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('追剧猫', 'https://zhuiyingmao5.com/', 'https://zhuiyingmao5.com/mxtheme/images/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('51剧搜', 'https://51souju1.com/', 'https://51souju1.com/upload/site/20240308-1/d1b8cb820ccfd75329e10a9f4814d08b.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('搜片', 'https://soupian.pro/', 'https://51souju1.com/upload/site/20240308-1/d1b8cb820ccfd75329e10a9f4814d08b.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('影猫の仓库', 'https://ymck.pro/', 'https://ymck.pro/upload/site/20230825-1/5c00fbcfb4ff0737d3c8320d30b2d1de.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('影搜', 'https://xn--p3tv7h.com/', 'https://ymck.pro/upload/site/20230825-1/5c00fbcfb4ff0737d3c8320d30b2d1de.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('MXONE', 'https://www.xmxone.cn/', 'https://www.xmxone.cn/mxtheme/images/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('7080影视搜', 'https://7080.wang/', 'https://7080.wang/img/index-logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('麻雀视频', 'https://www.mqtv.cc/', 'https://www.mqtv.cc/asset/img/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('看片狂人', 'https://kpkuang.sbs/', 'https://kpkuang.sbs/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('A8影视', 'https://a8ys.vip/', 'https://7080.wang/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('麦田影院', 'https://www.mtyy1.com/', 'https://www.mtyy1.com/static/ds6/img/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('看B站', 'https://kanb.tv/#google_vignette', 'https://www.mtyy1.com/static/ds6/img/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('侠客影视', 'http://xkys.link/', 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('可达影视', 'https://www.kedays.org/', 'https://www.kedays.org/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('饺子影院', 'https://www.jiaozi.me/', 'https://www.jiaozi.me/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('厂长资源', 'https://www.czys.pro/', 'https://www.czys.pro/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('NO视频', 'https://www.novipnoad.net/', 'https://www.czys.pro/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('低端影视', 'https://ddys.pro/', 'https://ddys.pro/favicon-32x32.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('奈飞工厂', 'https://www.netflixgc.com/', 'https://www.netflixgc.com/.safeline/static/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('在线之家', 'https://www.zxzjhd.com/', 'https://www.zxzjhd.com/statics/img/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('热门网络短剧', 'http://www.yingshicun.com/', 'http://www.yingshicun.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('NEX字幕组', 'https://nz99.xyz/index.html', 'https://nz99.xyz/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('MYFREEMP3', 'https://tool.liumingye.cn/music/?page=searchPage#/', 'https://ae01.alicdn.com/kf/H085a1499a38d4d8a920a396abceffa2bW.jpg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('熊猫无损音乐', 'https://www.xmwav.com/', 'https://www.xmwav.com/assets/picture/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('放屁音乐网', 'https://www.fangpi.net/', 'https://www.fangpi.net/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('88影视网', 'https://www.88tvs.cn/', 'https://www.88tvs.cn/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('鸭梨视讯', 'https://www.yalishi.com/', 'https://www.yalishi.com/template/a_0011/assets/images/favicon.ico?v=20230523');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('旋风视频', 'https://miao101.com/', 'https://miao101.com/fs/static/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('磁力熊', 'https://www.cilixiong.org/', 'https://www.cilixiong.org/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('鸭梨视讯', 'https://www.yalishi.com/', 'https://www.yalishi.com/template/a_0011/assets/images/favicon.ico?v=20230523');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('PDF转图片', 'https://www.jyshare.com/front-end/7271/', 'https://static.jyshare.com/images/c-runoob-logo.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('在线白板', 'https://visionon.cn/clipboard', 'https://visionon.cn/v-logo-2.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('画板', 'https://excalidraw.com/', 'https://excalidraw.com/favicon-32x32.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('icon图标在线生成', 'https://www.ico51.cn/', 'https://www.ico51.cn/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('图床', 'https://telegraph-image-92x.pages.dev/', 'https://telegraph-image-92x.pages.dev/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('ME2在线工具', 'https://www.metools.info/?ref=www.myxinwen.top', 'https://www.metools.info/skin/images/toolicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('视频网址解析下载', 'https://greenvideo.cc/', 'https://greenvideo.cc/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('PS在线版', 'https://www.nuanque.com/ps/', 'https://www.nuanque.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('颜色对照表', 'https://bbs.bianzhirensheng.com/color01.html', 'https://bbs.bianzhirensheng.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('图好快', 'https://www.tuhaokuai.com/?ref=www.myxinwen.top', 'https://www.tuhaokuai.com/themes/default/images/fav.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('SVG在线编辑器', 'https://www.jyshare.com/more/svgeditor/?ref=www.myxinwen.top', 'https://www.jyshare.com/more/svgeditor/images/favicon.svg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('icon图标制作', 'https://www.dute.org/ico-converter?ref=www.myxinwen.top', 'https://cdn-v2.tool.dute.me/assets/images/web/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('PDF工具', 'https://pdf.io/tw/?ref=www.myxinwen.top', 'https://pdf.io/static/i/v3/favicon.svg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('在线转换器', 'https://cn.office-converter.com/?ref=www.myxinwen.top', 'https://cn.office-converter.com/Online-Converter/Office-Converter.svg');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('万兴hiPDF', 'https://www.hipdf.cn/?ref=www.myxinwen.top', 'https://www.hipdf.cn/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('iLovePDF', 'https://www.ilovepdf.com/zh-cn?ref=www.myxinwen.top', 'https://www.ilovepdf.com/img/favicons-pdf/favicon-32x32.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('mmPlayer', 'https://netease-music.fe-mm.com/#/music/details/19723756', 'https://netease-music.fe-mm.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('果核剥壳', 'https://www.ghxi.com/', 'https://www.ghxi.com/wp-content/uploads/2019/12/2020logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('盘友网', 'https://panyq.com/', 'https://panyq.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('口袋云盘', 'https://www.woxiangsou.com/home?deviceId=e721fe11-2303-411a-9b70-b66bf19ce610&channelId=4', 'http://hy.cdn.sohucs.com/sns_clouddisk_search/prod/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('UP云搜', 'https://www.upyunso.com/', 'https://cdn.tkk78.com/upyunso/web_static/static/img/upso_mlogo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('天翼搜', 'https://www.tianyiso.com/', 'https://www.tianyiso.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('小纸条', 'https://ali.gitcafe.ink/', '');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('易搜', 'https://yiso.fun/', 'https://yiso.fun/static/img/logo.7101c44.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('狸猫盘', 'https://www.alipansou.com/', 'https://www.alipansou.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('小马盘', 'https://www.xiaomapan.com/#/main/search?restype=1', 'https://res.hexiaotu.com/sousuo/xiaomapan/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('阿众软件库', 'https://www.azhongruanjian.com/', 'https://www.azhongruanjian.com/wp-content/uploads/2024/06/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('吾爱破解', 'https://www.52pojie.cn/portal.php', 'https://static.52pojie.cn/static/image/common/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('华军软件园', 'https://www.onlinedown.net/', 'https://res.njxzwh.com/onlinedown/images/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('西部落', 'https://www.xibuluo.com/', 'https://www.xibuluo.com/View/images/logo.xibuluo.com.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('423Down', 'https://www.423down.com/#google_vignette', 'https://www.423down.com/wp-content/themes/D7/img/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('异星软件空间', 'https://www.yxssp.com/#google_vignette', 'https://www.yxssp.com/wp-content/uploads/2017/12/yx250.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('腾龙工作室', 'https://www.tenlonstudio.com/', 'https://www.tenlonstudio.com/wp-content/uploads/2019/09/new-logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('小刀娱乐网', 'https://xd.x6d.com/html/23.html', 'https://xd.x6d.com/static/images/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('懒得勤快', 'https://masuit.net/', 'https://masuit.net/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('亦是美', 'http://www.yishimei.cn/', 'https://www.xibuluo.com/View/images/logo.xibuluo.com.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('蓝点网', 'https://www.landiannews.com/', 'https://static.lancdn.com/landian/v4.0.1/images/logo_light.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('飘雪网', 'https://www.chinapyg.com/', 'https://www.xibuluo.com/View/images/logo.xibuluo.com.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('小白课堂', 'http://www.itmind.net/collect', 'http://www.itmind.net/wp-content/uploads/2020/09/1599721603-322895ededfd717.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('图欧学习导航', 'https://tuostudy.upnb.top/', 'https://tuostudy.upnb.top/wp-content/uploads/2025/03/主题logo黑色NEW.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('阿虚同学的储物间', 'https://axutongxue.com/', 'https://axutongxue.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('陈蛋蛋的宝藏库', 'http://chendandan.ysepan.com/', 'http://chendandan.ysepan.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('小帅同学的储物间', 'https://xiaoshuai.link/locker/', 'https://xiaoshuai.link/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('金榜题名', 'http://qzbltushu.ysepan.com/', 'http://qzbltushu.ysepan.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('山海之花', 'https://cbge.top/ziyuan', 'https://cbge.top/wp-content/uploads/2024/03/cropped-2024030919225699.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('懒人找资源', 'https://lazybook.fun/#/', 'https://lazybook.fun/lazy.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('咖喱君的资源目录', 'https://flowus.cn/galijun/share/de0f6d2f-df17-4075-86ed-ebead0394a77', 'https://cdn2.flowus.cn/fe-web-app-images/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('小彬网', 'https://www.xiaobinwang.cc/', 'https://www.xiaobinwang.cc/zb_users/upload/2022/10/202210011664608340207364.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('资源网', 'https://heeee.com/', 'https://heeee.com/wp-content/uploads/2023/12/logo.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('禧客小店', 'http://xikestore.ysepan.com/', 'http://xikestore.ysepan.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('小z博客', 'https://blog.xiaoz.org/', 'https://blog.xiaoz.org/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('超能搜', 'https://www.chaonengsou.com/', 'https://www.chaonengsou.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('设计导航', 'https://hao.shejidaren.com/', 'https://hao.shejidaren.com/images/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('喜欢书签', 'https://www.likebookmark.com/', 'https://www.likebookmark.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('阡途导航', 'http://123.tentod.com/', 'http://123.tentod.com/images/icons/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('星云导航', 'https://www.xygalaxy.com/', 'https://www.xygalaxy.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('夸克资源小海洋', 'https://link3.cc/quarkresource', 'https://link3.cc/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('奔跑中的奶酪', 'https://www.runningcheese.com/', 'https://www.runningcheese.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('果汁导航', 'http://guozhivip.com/', 'http://guozhivip.com/images/ic.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('爱达杂货铺', 'https://adzhp.cc/', 'https://adzhp.cc/wp-content/uploads/2020/02/A-win.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('轻工具导航', 'https://qinggongju.com/', 'https://qinggongju.com/wp-content/uploads/2023/11/logo1.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('不死鸟-每日分享', 'https://iui.su/fx/', 'https://iui.su/2025.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('IMyshare', 'https://imyshare.com/', 'https://imyshare.com/favicon.ico');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('万人迷吧', 'https://www.wanrenmi8.com/cn/index.html', 'https://www.wanrenmi8.com/assets/images/1.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('免费AI工具导航网站', 'https://nav.laogou717.com/', 'https://nav.laogou717.com/images/favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('阅文网址大全', 'https://www.myxinwen.top/', 'https://www.myxinwen.top/wp-content/uploads/2024/05/0000-1.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('终极导航', 'https://www.zjnav.com/', 'https://www.zjnav.com/wp-content/uploads/2024/01/1705467656-favicon.png');
INSERT INTO `bookmark` (`name`, `url`, `icon`) VALUES ('硬核指南', 'https://yinghezhinan.com/', 'https://yinghezhinan.com/statics/images/favicon.webp');
